# **Step1: Import Library**

In [1]:
import pandas as pd

# **Step2: Read Dataset**

In [2]:
df = pd.read_csv('https://github.com/YBIFoundation/Dataset/raw/main/Diabetes.csv')

In [3]:
df.head()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   pregnancies  768 non-null    int64
 1   glucose      768 non-null    int64
 2   diastolic    768 non-null    int64
 3   triceps      768 non-null    int64
 4   insulin      768 non-null    int64
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64
 8   diabetes     768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [5]:
df.describe()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

# **Step3: Define y and X**

In [6]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [7]:
y = df['diabetes']

In [8]:
X = df[['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age']]

# **Step 4: Train Test Split**

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=2529)

# **Step 5: Select Model**

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
logit = LogisticRegression(max_iter=500)

# **Step 6: Train Model**

In [13]:
logit.fit(X_train,y_train)

LogisticRegression(max_iter=500)

In [14]:
logit.intercept_

array([-8.29760943])

In [15]:
logit.coef_

array([[ 1.03970514e-01,  3.60029168e-02, -2.05052109e-02,
        -2.05049684e-03,  1.77862901e-04,  8.58797145e-02,
         9.55475356e-01,  2.45882609e-02]])

# **Step 7: Prediction**

In [16]:
y_pred = logit.predict(X_test)

In [17]:
y_pred

array([0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [18]:
logit.predict_proba(X_test)

array([[0.93688745, 0.06311255],
       [0.61371626, 0.38628374],
       [0.22439141, 0.77560859],
       [0.64999186, 0.35000814],
       [0.62008381, 0.37991619],
       [0.25605981, 0.74394019],
       [0.05520428, 0.94479572],
       [0.1669316 , 0.8330684 ],
       [0.97517802, 0.02482198],
       [0.42525475, 0.57474525],
       [0.97516554, 0.02483446],
       [0.09677977, 0.90322023],
       [0.81246867, 0.18753133],
       [0.97121538, 0.02878462],
       [0.86120402, 0.13879598],
       [0.418361  , 0.581639  ],
       [0.2935365 , 0.7064635 ],
       [0.50320528, 0.49679472],
       [0.95674442, 0.04325558],
       [0.8345472 , 0.1654528 ],
       [0.34135868, 0.65864132],
       [0.46409039, 0.53590961],
       [0.77744614, 0.22255386],
       [0.9860552 , 0.0139448 ],
       [0.83451069, 0.16548931],
       [0.88661203, 0.11338797],
       [0.78063992, 0.21936008],
       [0.42780236, 0.57219764],
       [0.93571641, 0.06428359],
       [0.70809657, 0.29190343],
       [0.96721801, 0.03278199],
       [0.62738667, 0.37261333],
       [0.7511063 , 0.2488937 ],
       [0.52783854, 0.47216146],
       [0.22194601, 0.77805399],
       [0.59175136, 0.40824864],
       [0.8824188 , 0.1175812 ],
       [0.41896033, 0.58103967],
       [0.68272257, 0.31727743],
       [0.01115081, 0.98884919],
       [0.94468943, 0.05531057],
       [0.99421956, 0.00578044],
       [0.93182024, 0.06817976],
       [0.40055108, 0.59944892],
       [0.8939958 , 0.1060042 ],
       [0.29927974, 0.70072026],
       [0.1903394 , 0.8096606 ],
       [0.90738371, 0.09261629],
       [0.50943148, 0.49056852],
       [0.56766908, 0.43233092],
       [0.96945637, 0.03054363],
       [0.10790174, 0.89209826],
       [0.62857294, 0.37142706],
       [0.91643739, 0.08356261],
       [0.79937425, 0.20062575],
       [0.73573112, 0.26426888],
       [0.36816385, 0.63183615],
       [0.96039453, 0.03960547],
       [0.924467  , 0.075533  ],
       [0.20439401, 0.79560599],
       [0.63008261, 0.36991739],
       [0.90033685, 0.09966315],
       [0.54573594, 0.45426406],
       [0.5869192 , 0.4130808 ],
       [0.69502535, 0.30497465],
       [0.0185754 , 0.9814246 ],
       [0.9723634 , 0.0276366 ],
       [0.9777038 , 0.0222962 ],
       [0.16174208, 0.83825792],
       [0.80056543, 0.19943457],
       [0.0759748 , 0.9240252 ],
       [0.74851158, 0.25148842],
       [0.93705894, 0.06294106],
       [0.75524692, 0.24475308],
       [0.63388583, 0.36611417],
       [0.96253629, 0.03746371],
       [0.94619334, 0.05380666],
       [0.89058487, 0.10941513],
       [0.91350394, 0.08649606],
       [0.93956583, 0.06043417],
       [0.87544182, 0.12455818],
       [0.84512797, 0.15487203],
       [0.39097127, 0.60902873],
       [0.4544885 , 0.5455115 ],
       [0.84832589, 0.15167411],
       [0.75529825, 0.24470175],
       [0.07786958, 0.92213042],
       [0.95946426, 0.04053574],
       [0.42528433, 0.57471567],
       [0.59338846, 0.40661154],
       [0.40764056, 0.59235944],
       [0.75681952, 0.24318048],
       [0.2391575 , 0.7608425 ],
       [0.6918317 , 0.3081683 ],
       [0.9631851 , 0.0368149 ],
       [0.75096131, 0.24903869],
       [0.79164186, 0.20835814],
       [0.77898883, 0.22101117],
       [0.93016115, 0.06983885],
       [0.7429037 , 0.2570963 ],
       [0.21449327, 0.78550673],
       [0.81809571, 0.18190429],
       [0.84395081, 0.15604919],
       [0.05918873, 0.94081127],
       [0.22024473, 0.77975527],
       [0.82825928, 0.17174072],
       [0.9141742 , 0.0858258 ],
       [0.17454115, 0.82545885],
       [0.82201782, 0.17798218],
       [0.13386056, 0.86613944],
       [0.70809556, 0.29190444],
       [0.90846619, 0.09153381],
       [0.9810656 , 0.0189344 ],
       [0.08326965, 0.91673035],
       [0.28185195, 0.71814805],
       [0.60283325, 0.39716675],
       [0.8836482 , 0.1163518 ],
       [0.96672587, 0.03327413],
       [0.92964681, 0.07035319],
       [0.87668115, 0.12331885],
       [0.99118426, 0.00881574],
       [0.20065439, 0.79934561],
       [0.92486484, 0.07513516],
       [0.38465027, 0.61534973],
       [0.97148362, 0.02851638],
       [0.78787195, 0.21212805],
       [0.09819299, 0.90180701],
       [0.96167776, 0.03832224],
       [0.22689602, 0.77310398],
       [0.87677853, 0.12322147],
       [0.80602352, 0.19397648],
       [0.17621616, 0.82378384],
       [0.88163568, 0.11836432],
       [0.87043257, 0.12956743],
       [0.86150657, 0.13849343],
       [0.09165068, 0.90834932],
       [0.61002592, 0.38997408],
       [0.05307629, 0.94692371],
       [0.90036378, 0.09963622],
       [0.6752326 , 0.3247674 ],
       [0.59768197, 0.40231803],
       [0.90352647, 0.09647353],
       [0.97713859, 0.02286141],
       [0.16379449, 0.83620551],
       [0.88106596, 0.11893404],
       [0.55173239, 0.44826761],
       [0.97761316, 0.02238684],
       [0.87667996, 0.12332004],
       [0.35460672, 0.64539328],
       [0.94527179, 0.05472821],
       [0.85184784, 0.14815216],
       [0.9034435 , 0.0965565 ],
       [0.84660198, 0.15339802],
       [0.55025079, 0.44974921],
       [0.51483472, 0.48516528],
       [0.30196545, 0.69803455],
       [0.24392994, 0.75607006],
       [0.79621574, 0.20378426],
       [0.96790759, 0.03209241],
       [0.86069825, 0.13930175],
       [0.93851519, 0.06148481],
       [0.64647228, 0.35352772],
       [0.87525871, 0.12474129],
       [0.77997987, 0.22002013],
       [0.70430736, 0.29569264],
       [0.98201034, 0.01798966],
       [0.97151629, 0.02848371],
       [0.70808604, 0.29191396],
       [0.95727452, 0.04272548],
       [0.85073719, 0.14926281],
       [0.3122003 , 0.6877997 ],
       [0.53754865, 0.46245135],
       [0.64683912, 0.35316088],
       [0.4092417 , 0.5907583 ],
       [0.95529304, 0.04470696],
       [0.88087916, 0.11912084],
       [0.70873928, 0.29126072],
       [0.24060402, 0.75939598],
       [0.68581942, 0.31418058],
       [0.87875128, 0.12124872],
       [0.94055592, 0.05944408],
       [0.89088659, 0.10911341],
       [0.9050546 , 0.0949454 ],
       [0.66142976, 0.33857024],
       [0.85398516, 0.14601484],
       [0.91412977, 0.08587023],
       [0.73864206, 0.26135794],
       [0.98786572, 0.01213428],
       [0.34170064, 0.65829936],
       [0.95695789, 0.04304211],
       [0.77441117, 0.22558883],
       [0.91435881, 0.08564119]])

# **Step 8: Model Evaluation**

In [19]:
from sklearn.metrics import confusion_matrix, classification_report

In [20]:
confusion_matrix(y_test,y_pred)

array([[108,  10],
       [ 33,  41]])

In [21]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.92      0.83       118
           1       0.80      0.55      0.66        74

    accuracy                           0.78       192
   macro avg       0.78      0.73      0.74       192
weighted avg       0.78      0.78      0.77       192

# **Explanatory Model**

In [22]:
import statsmodels.api as sm
X1 = sm.add_constant(X)
print(sm.Logit(y,X1).fit().summary())

Optimization terminated successfully.
         Current function value: 0.470993
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:               diabetes   No. Observations:                  768
Model:                          Logit   Df Residuals:                      759
Method:                           MLE   Df Model:                            8
Date:                Tue, 20 Feb 2024   Pseudo R-squ.:                  0.2718
Time:                        10:35:52   Log-Likelihood:                -361.72
converged:                       True   LL-Null:                       -496.74
Covariance Type:            nonrobust   LLR p-value:                 9.652e-54
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -8.4047      0.717    -11.728      0.000      -9.809      -7.000
pregnancies     0.1232      0.032      3.840      0.000       0.060       0.186
glucose         0.0352      0.004      9.481      0.000       0.028       0.042
diastolic      -0.0133      0.005     -2.540      0.011      -0.024      -0.003
triceps         0.0006      0.007      0.090      0.929      -0.013       0.014
insulin        -0.0012      0.001     -1.322      0.186      -0.003       0.001
bmi             0.0897      0.015      5.945      0.000       0.060       0.119
dpf             0.9452      0.299      3.160      0.002       0.359       1.531
age             0.0149      0.009      1.593      0.111      -0.003       0.033
===============================================================================